name: iris_route
description: A package for routing and navigation.
version: 0.0.29

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^2.0.2
  lints: ^2.1.1
  test: ^1.24.4


flutter:


