name: iris_route
description: A package for routing and navigation.
version: 0.0.1

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  lints: ^2.0.1
  test: ^1.24.1


flutter:


