name: iris_route
description: A package for routing and navigation.
version: 0.0.32

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^3.0.1
  lints: ^3.0.0
  test: ^1.25.0


flutter:


